title: Anchen Sun 
description: ECE Ph.D. Candidate
site_title: '@anchensun - Anchen Sun'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: anchensun
blog_url: https://anchensun.github.io
email: asun@miami.edu
keybase_username: anchensun
twitter_username: anchensun
reddit_username: anchensun

# absolute or relative
profile_picture: assets/images/Anchen.jpg

# Google Analytics ID
google_analytics: 
